dist: bionic
addons:
    apt:
        packages:
            - texlive
            - texlive-lang-english
            - texlive-lang-french
            - texlive-latex-extra
            - texlive-science
            - texlive-bibtex-extra
            - biber
services:
  - docker

language: generic

before_install:
    - git submodule update --init --recursive

script:
    - ci/build.sh

deploy:
  provider: releases
  api_key: "ad236a3c83e2b5b20d5ab24c88077f0961f08333
  file: "main.pdf"
  skip_cleanup: true
  on:
    tags: false
